<?php

/**
 * @file
 * Module file for bt_cms.
 */

use Drupal\user\Entity\User;
use Drupal\personas\PersonaUtility;

/**
 * Implements hook_menu_local_actions_alter().
 */
function bt_cms_menu_local_actions_alter(&$local_actions) {
  $local_actions['node.add_page']['appears_on'][0] = 'page_manager.page_view_app_website_content_app_website_content-panels_variant-0';
  $local_actions['node.add_page']['appears_on'][1] = 'page_manager.page_view_app_website_content_app_website_content-panels_variant-1';

}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function bt_cms_menu_local_tasks_alter(&$data, $route_name) {
  $current_user = \Drupal::service('current_user');
  $user_id = $current_user->id();
  $user_account = User::load($user_id);

  $routes = [
    'page_manager.page_view_app_app-panels_variant-0',
    'bt_page_drag_and_drop',
    'page_manager.page_view_app_website_app_website-panels_variant-0',
    'page_manager.page_view_app_website_content_app_website_content-panels_variant-0',
    'page_manager.page_view_app_website_content_app_website_content-panels_variant-1',
    'page_manager.page_view_app_website_comments_app_website_comments-panels_variant-0',
    'page_manager.page_view_app_website_documents_app_website_documents-panels_variant-0',
    'page_manager.page_view_app_website_documents_app_website_documents-panels_variant-1',
    'page_manager.page_view_app_website_media_app_website_media-panels_variant-0',
    'page_manager.page_view_app_website_media_app_website_media-panels_variant-1',
    'page_manager.page_view_app_website_polls_app_website_polls-panels_variant-0',
    'page_manager.page_view_app_website_forums_app_website_forums-panels_variant-0',
    'page_manager.page_view_app_website_faq_app_website_faq-panels_variant-0',
    'page_manager.page_view_app_website_blocks_app_website_blocks-panels_variant-0',
  ];

  if (in_array($route_name, $routes)) {
    if (PersonaUtility::hasPersona($user_account, 'bt_content_editor_publisher')) {
      unset($data['tabs'][0]['bt_website_content_writer_task']);
      unset($data['tabs'][1]['bt_website_content_writer_default_task']);
      unset($data['tabs'][0]['bt_website_documents_writer_task']);
      unset($data['tabs'][0]['bt_website_media_writer_task']);
    }
    elseif (PersonaUtility::hasPersona($user_account, 'bt_content_creator')) {
      unset($data['tabs'][0]['bt_website_content_admin_task']);
      unset($data['tabs'][1]['bt_website_content_admin_default_task']);
      unset($data['tabs'][0]['bt_website_documents_admin_task']);
      unset($data['tabs'][0]['bt_website_media_admin_task']);
    }
  }

}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function bt_cms_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'node') {
    if (isset($fields['title'])) {
      $fields['title']->setDisplayConfigurable('view', TRUE);
    }
  }
  // Alter the mymodule_text field to use a custom class.
  if ($entity_type->id() == 'block_content') {
    $fields['info']->setLabel('Block Name');
    $fields['info']->setDescription('The name by which the block will be displayed in the list of custom blocks.');
  }

}

/**
 * Implements hook_entity_type_alter().
 */
function bt_cms_entity_type_alter(array &$entity_types) {
  $entity_types['node']->setHandlerClass('route_provider', ['html' => 'Drupal\bt_cms\AlterNodeRouteProvider']);
  $entity_types['node']->setHandlerClass('view_builder', 'Drupal\bt_cms\CustomNodeViewBuilder');

}

/**
 * Implements hook_node_links_alter().
 */
function bt_cms_node_links_alter(&$links, $entity, &$context) {
  if ($entity->getEntityTypeId() == 'node') {
    $bundle = $entity->bundle();
    $view_mode = $context['view_mode'];
    $links['#theme'] = 'links__' . $bundle . '_' . $view_mode;
  }

}
