<?php

/**
 * @file
 * Install, update and uninstall functions for bt_cms.
 */

/**
 * Implements hook_install().
 */
function bt_cms_install() {
  // Disable taxonomy_term view.
  \Drupal::entityTypeManager()->getStorage('view')
    ->load('taxonomy_term')
    ->setStatus(FALSE)
    ->save();

  // Disable comment view.
  \Drupal::entityTypeManager()->getStorage('view')
    ->load('comment')
    ->setStatus(FALSE)
    ->save();
}
